# Generated by Django 3.0.1 on 2019-12-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topmovie',
            name='image',
            field=models.ImageField(default=0, upload_to='static/images/', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
