# Generated by Django 3.0.1 on 2019-12-23 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20191222_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymovies',
            name='add',
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
        migrations.DeleteModel(
            name='MyMovies',
        ),
    ]
