# Generated by Django 3.0.1 on 2019-12-27 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20191223_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkmovie',
            name='rec',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Recommended', verbose_name='Рекомендации'),
            preserve_default=False,
        ),
    ]
