# Generated by Django 3.0.1 on 2019-12-27 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_bookmarkmovie_rec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarkmovie',
            name='rec',
        ),
    ]
