# Generated by Django 3.0.1 on 2019-12-27 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_remove_bookmarkmovie_rec'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recommended',
        ),
    ]
