# Generated by Django 3.0.1 on 2019-12-27 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_delete_recommended'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookmarkmovie',
            table=None,
        ),
    ]
